name: newComment
on:
  issue_comment:
    types: [created]
  discussion_comment:
    types: [created]

jobs:
  init:
    name: commentInit
    runs-on: ubuntu-latest
    steps:
      - name: Comment Hello World
        id: commentHelloWorld
        run: |
          echo "Comment Hello World"

  dispatch-run:
    name: dispatchRun
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/run ') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Dispatch Run for comment
        id: init
        run: |
          echo "[task] Dispatch run Hello World" ${{ github.event.comment.body }}

      - name: Trigger Workflow
        uses: ./.github/actions/runTestAction
        with:
          input1: testFromNewCommentWorkflow1


  dispatch-rerun:
    name: dispatchRerun
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/rerun ') }}
    steps:
      - name: Dispatch Rerun for comment
        id: init
        run: |
          echo "[main] Dispatch rerun Hello World" ${{ github.event.comment.body }}
