name: newComment
on:
  issue_comment:
    types: [created]

jobs:
  init:
    name: commentInit
    runs-on: ubuntu-latest
    steps:
      - name: Comment Hello World
        id: commentHelloWorld
        run: |
          echo "Comment Hello World"

  dispatch-run:
    name: dispatchRun
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }} && contains(github.event.comment.body, '/run')
    steps:
      - name: Dispatch Run for comment
        id: init
        run: |
          echo "Dispatch run Hello World"
