name: NewCommit
on:
  push:
    branches:
      - '**' # matches every branch
    paths:
      - '**' # matches any change

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest
    steps:
      - name: Commit Hello World
        id: commitHelloWorld
        run: |
          echo "New Commit Hello World"
