name: newComment
on:
  issue_comment:
    types: [created]
  discussion_comment:
    types: [created]

jobs:
  init:
    name: commentInit
    runs-on: ubuntu-latest
    steps:
      - name: Comment Hello World
        id: commentHelloWorld
        run: |
          echo "Comment Hello World"

  dispatch-run:
    name: dispatchRun
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
      - name: Dispatch Run for comment
        if: startsWith(github.event.comment.body, '/run ')
        id: init
        run: |
          echo "Dispatch run Hello World" ${{ github.event.comment.body }}

  dispatch-rerun:
    name: dispatchRerun
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
      - name: Dispatch Rerun for comment
        if: startsWith(github.event.comment.body, '/rerun ')
        id: init
        run: |
          echo "Dispatch rerun Hello World" ${{ github.event.comment.body }}
