name: NewCommit
on:
  push:
    branches:
      - '**' # matches every branch
    paths:
      - '**' # matches any change


jobs:
  init:
    name: Init
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        id: helloWorld
        run: |
          echo "Hello World Test"
