name: newComment
on:
  issue_comment:
    types: [created]
  discussion_comment:
    types: [created]

permissions: write-all

jobs:
  init:
    name: commentInit
    runs-on: ubuntu-latest
    steps:
      - name: Comment Hello World
        id: commentHelloWorld
        run: |
          echo "Comment Hello World"

  dispatch-run:
    name: dispatchRun
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/run ') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: jungwinter/split@v2
        id: split
        with:
          msg: ${{ github.event.comment.body }}
          separator: ' '
          maxsplit: 2

      - name: Dispatch Run for comment
        id: init
        run: |
          echo "[task] Dispatch run Hello World" ${{ github.event.comment.body }}

      - uses: LouisBrunner/checks-action@v1.3.1
        id: check
        with:
          sha: ${{ github.sha }}
#          token: ${{ steps.get_installation_token.outputs.token }}
#          token: ${{ github.token }}
          token: ${{ secrets.GITHUB_TOKEN }}
#          token: ${{ secrets.MAREK_TOKEN_2 }}
          name: Second Job
          status: in_progress

      - name: Trigger Workflow
        uses: ./.github/actions/runTestAction
        with:
          input1: ${{ steps.split.outputs._1 }} [${{ steps.split.outputs.length }}]

      - uses: LouisBrunner/checks-action@v1.3.1
        if: failure()
        with:
          sha: ${{ github.sha }}
#          token: ${{ steps.get_installation_token.outputs.token }}
#          token: ${{ github.token }}
          token: ${{ secrets.GITHUB_TOKEN }}
#          token: ${{ secrets.MAREK_TOKEN_2 }}
          name: Second Job
          conclusion: ${{ job.status }}
          output: |
            {"summary":""}

  dispatch-rerun:
    name: dispatchRerun
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/rerun ') }}
    steps:
      - name: Dispatch Rerun for comment
        id: init
        run: |
          echo "[main] Dispatch rerun Hello World" ${{ github.event.comment.body }}
