name: runTestAction
on:
  workflow_dispatch:
    inputs:
      input1:
        type: string
        required: false
        default: 'testString1'
        description: 'Test input 1'

jobs:
  init:
    name: runInit
    runs-on: ubuntu-latest
    steps:
      - name: Run Hello World
        id: runHelloWorld
        run: |
          echo "RUN Hello World" ${{ inputs.input1 }}
